import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Multi-sidebar configuration for Builder and Core Concepts sections
 *
 * - builderSidebar: Usage-focused docs (tutorials, guides, reference)
 *   Canonical source: docs/builder/ (get-started, smart-contracts, etc.)
 *   Ingested content: docs/builder/tutorials/, docs/builder/client/
 *
 * - coreConceptsSidebar: Architecture/internals (protocol, VM, proving)
 *   Canonical source: Landing page in docs/core-concepts/index.md
 *   Ingested content: docs/core-concepts/protocol/, miden-vm/, compiler/, node/
 *
 * ARCHITECTURE NOTE:
 * External docs are ingested at build time via deploy-docs.yml into:
 *   - Core Concepts docs → docs/core-concepts/*
 *   - Builder docs → docs/builder/tutorials/, docs/builder/tools/client/
 * These paths are cleaned and re-synced on each build from source repos.
 */
const sidebars: SidebarsConfig = {
  builderSidebar: [
    // ── GETTING STARTED
    {
      type: "html",
      value: '<span class="sidebar-section">Getting Started</span>',
    },
    { type: "doc", id: "builder/index" },
    {
      type: "category",
      label: "Get Started",
      link: { type: "doc", id: "builder/get-started/index" },
      items: [{ type: "autogenerated", dirName: "builder/get-started" }],
    },

    // ── BUILD
    {
      type: "html",
      value: '<span class="sidebar-section">Build</span>',
    },
    {
      type: "category",
      label: "Smart Contracts",
      link: { type: "doc", id: "builder/smart-contracts/index" },
      items: [{ type: "autogenerated", dirName: "builder/smart-contracts" }],
    },
    {
      type: "category",
      label: "Tutorials",
      link: { type: "doc", id: "builder/tutorials/rust-compiler/index" },
      items: [{ type: "autogenerated", dirName: "builder/tutorials" }],
    },
    {
      type: "category",
      label: "Guides",
      items: [{ type: "autogenerated", dirName: "builder/guides" }],
    },
    {
      type: "category",
      label: "Tools",
      link: { type: "doc", id: "builder/tools/index" },
      items: [{ type: "autogenerated", dirName: "builder/tools" }],
    },

    // ── SOLUTIONS
    {
      type: "html",
      value: '<span class="sidebar-section">Solutions</span>',
    },
    {
      type: "category",
      label: "Guardian",
      link: { type: "doc", id: "builder/miden-guardian/index" },
      items: [{ type: "autogenerated", dirName: "builder/miden-guardian" }],
    },
    {
      type: "category",
      label: "Private Multisig",
      link: { type: "doc", id: "builder/private-multisig/index" },
      items: [
        { type: "autogenerated", dirName: "builder/private-multisig" },
      ],
    },

    // ── REFERENCE
    {
      type: "html",
      value: '<span class="sidebar-section">Reference</span>',
    },
    {
      type: "category",
      label: "Migration",
      link: { type: "doc", id: "builder/migration/index" },
      items: [{ type: "autogenerated", dirName: "builder/migration" }],
    },
    { type: "doc", id: "builder/glossary" },
  ],

  // Core Concepts: landing page + ingested external content
  // Note: External docs are ingested during CI/CD build via deploy-docs.yml
  // For local dev, only the landing page exists; categories appear when content is ingested
  coreConceptsSidebar: [{ type: "autogenerated", dirName: "core-concepts" }],
};

export default sidebars;
